'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("frmMidiControllerPlayer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property After() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("After", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property AfterLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AfterLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property AfterMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AfterMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AfterToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AfterToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Better() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Better", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property BetterLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("BetterLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property BetterMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("BetterMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BetterToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BetterToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DLabel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DLabel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Dlabel0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dlabel0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DoIt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DoIt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property DoItLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DoItLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property DoItMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DoItMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DoItToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DoItToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Ever() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ever", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property EverLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("EverLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property EverMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("EverMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property EverToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EverToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Faster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Faster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property FasterLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FasterLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property FasterMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("FasterMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FasterToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FasterToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Harder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Harder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property Harder__Better__Faster__Stronger__Instrumental_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Harder__Better__Faster__Stronger__Instrumental_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property HarderLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HarderLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property HarderMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HarderMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HarderToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HarderToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Hour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property HourLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HourLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property HourMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HourMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HourToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HourToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MakeIt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MakeIt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property MakeItLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MakeItLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property MakeItMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MakeItMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MakeItToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MakeItToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MakesUs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MakesUs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property MakesUsLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MakesUsLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property MakesUsMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MakesUsMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MakesUsToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MakesUsToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MoreThan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MoreThan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property MoreThanLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MoreThanLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property MoreThanMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MoreThanMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MoreThanToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MoreThanToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Never() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Never", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property NeverLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NeverLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property NeverMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NeverMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NeverToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NeverToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Our() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Our", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property OurLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OurLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property OurMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OurMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OurToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OurToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property OverLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OverLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property OverMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OverMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OverToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OverToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property picBeat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picBeat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property picBeat2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picBeat2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property picBeat3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picBeat3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property picBeat4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picBeat4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Stronger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stronger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property StrongerLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("StrongerLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property StrongerMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("StrongerMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property StrongerToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StrongerToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WorkIs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WorkIs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property WorkIsLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WorkIsLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property WorkIsMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WorkIsMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WorkIsToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WorkIsToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WorkIt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WorkIt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property WorkItLow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WorkItLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Public ReadOnly Property WorkItMid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WorkItMid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WorkItToggle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WorkItToggle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
